### PR TITLE
Additional licences

### PR DESCRIPTION
**Pull request by tmp-hallenser**
Add the different versions of CC licenses (#622).

### CODE REVIEW

**Comment by ildyria** [comment]
Don't forget the default licenses in the config. ;) 
Also you have default licenses for albums and you have the "accepted values" in the diagnostic check.

**Comment by tmp-hallenser** [comment]
> Don't forget the default licenses in the config. ;)
> Also you have default licenses for albums and you have the "accepted values" in the diagnostic check.

Perhaps it's already too late, but where did I miss something?

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee/blob/master/app/Configs.php#L60
I thought you may want to make a "license" specific check. :)

Well I just had a look at : https://github.com/LycheeOrg/Lychee/blob/master/database/migrations/2019_09_28_171753_config_fix.php#L233
And I was expecting a check against licenses possibilities, but it is just "string required".

So indeed nothing needed more. :)

**Comment by tmp-hallenser** [comment]
> https://github.com/LycheeOrg/Lychee/blob/master/app/Configs.php#L60
> I thought you may want to make a "license" specific check. :)
> 
> Well I just had a look at : https://github.com/LycheeOrg/Lychee/blob/master/database/migrations/2019_09_28_171753_config_fix.php#L233
> And I was expecting a check against licenses possibilities, but it is just "string required".
> 
> So indeed nothing needed more. :)

please review.

**Review by ildyria — APPROVED** [review]

**Pull request merged**
