### PR TITLE
Fix untranslatable strings

### PR DESCRIPTION
**Pull request by qwerty287**
Add some strings that were hard-coded into the JS files. Also addresses https://github.com/LycheeOrg/Lychee/issues/923#issuecomment-778820674=

### CODE REVIEW

**Comment by ildyria** [comment]
LGTM you are just missing the strings in the other languages (it is currently complaining about Chinese)

**Comment by qwerty287** [comment]
OK, so it is necessary to add them (in English) to every other locale? Didn't know that, thanks!

**Comment by ildyria** [comment]
> OK, so it is necessary to add them (in English) to every other locale? Didn't know that, thanks!

yes, the idea being that if you want to translate to another language/improve a translation, you do no need to search for the missing entries, the untranslated ones are directly visible.

**Comment by qwerty287** [comment]
Done.

**Review by ildyria — APPROVED** [review]

**Pull request merged**
