### PR TITLE
update to version 4.3.6

### PR DESCRIPTION
**Pull request by ildyria**
To be merged after #1142 so we can make a proper release with all the latest changes before the refactoring of @nagmat84 :)

### CODE REVIEW

**Review by d7415 — APPROVED** [review]
Looks good at a glance. Need to make sure we release it though :)

**Comment by kamil4** [comment]
As I said on Gitter, I would like to merge at least a partial clean-up of the front end menus before we release a new version, as they are a hot mess at the moment. I'll try to find time in the next 24h

**Review by nagmat84 — CHANGES_REQUESTED** [review]
LGTM. But we should wait until [#278](https://github.com/LycheeOrg/Lychee-front/pull/278) and [#276](https://github.com/LycheeOrg/Lychee-front/pull/276) of the front-end have been merged.

This PR should include the merges of the front-end.

**Review by kamil4 — APPROVED** [review]

**Review by nagmat84 — APPROVED** [review]

**Comment by nagmat84** [comment]
The recent bug fixes to the front-end are merged and synced into this PR. I guess we are ready to push 4.3.6 out of the door.

@ildyria, may I let you do the honors?

**Pull request merged**
