### PR TITLE
Disable snq if secret is not set

### PR DESCRIPTION
**Pull request by ildyria**
Hopefully this will prevent future dependabots PR to fail and same for contributors.

### CODE REVIEW

**Review by d7415 — APPROVED** [review]
Not convinced there's any benefit to making dependabot weekly - they're rarely that frequent, so we'll just learn about problems later?

**Comment by d7415** [comment]
Ok, I see a lot today. But weekly probably means the same number of PRs but concentrated into one day a week.

I mostly see this as "eek, that's a lot of dependencies"

**Comment by ildyria** [comment]
> Ok, I see a lot today. But weekly probably means the same number of PRs but concentrated into one day a week.
> 
> I mostly see this as "eek, that's a lot of dependencies"

I wish some of those PR were compacted in a single one.

**Comment by d7415** [comment]
Definitely. This may be worth a look https://www.hrvey.com/blog/combine-dependabot-prs

Oh, it looks like that schedule doesn't change security PRs, so I retract my comment.

**Pull request merged**
