### PR TITLE
Add upload_processing_limit config variable

### PR DESCRIPTION
**Pull request by kamil4**
Server side of https://github.com/LycheeOrg/Lychee-front/pull/246

### CODE REVIEW

**Comment by sunosv** [comment]
Can the limit set to more than 4?  Could Set the values based on server performance?

**Comment by d7415** [comment]
> Can the limit set to more than 4? 

Looks like it

>Could Set the values based on server performance?

The user can make that decision. Automatically setting this seems way out of scope.

**Review by ildyria — APPROVED** [review]
LGTM.

**Comment by ildyria** [comment]
> Can the limit set to more than 4? Could Set the values based on server performance?

Once this is merged, you can just go into your advanced setting and change the value yourself. :)

**Comment by sunosv** [comment]
> Once this is merged, you can just go into your advanced setting and change the value yourself. :)

ok, one more question,When is the next version come out?

**Comment by ildyria** [comment]
> ok, one more question,When is the next version come out?

Please define "next" version:

- Do you mean 5.0 ?
- Do you mean 4.2.2 ?
- Do you mean on Docker ?
- Do you mean as a zip file ?

**Comment by sunosv** [comment]
> Please define "next" version:
> 
> * Do you mean 5.0 ?
> * Do you mean 4.2.2 ?
> * Do you mean on Docker ?
> * Do you mean as a zip file ?

Sorry,I mean the 4.2.2

**Comment by ildyria** [comment]
> > Please define "next" version:
> > 
> > * Do you mean 5.0 ?
> > * Do you mean 4.2.2 ?
> > * Do you mean on Docker ?
> > * Do you mean as a zip file ?
> 
> Sorry,I mean the 4.2.2

I would say, pretty much soon. Most likely once this is merged or after #907 is merged.

**Comment by ildyria** [comment]
@sunosv https://github.com/LycheeOrg/Lychee/releases/tag/v4.2.2 :smiley:

**Comment by sunosv** [comment]
> @sunosv https://github.com/LycheeOrg/Lychee/releases/tag/v4.2.2 😃

 😃 Finally, thank you!

**Pull request merged**
