### PR TITLE
Add QR code locales

### PR DESCRIPTION
**Pull request by qwerty287**
https://github.com/LycheeOrg/Lychee-front/pull/287

### CODE REVIEW

**Review by kamil4 — APPROVED** [review]

**Comment by nagmat84** [comment]
Here is your rebased branch although it seems it is not necessary: https://github.com/LycheeOrg/Lychee/tree/qrcode-35_rebased

**Comment by qwerty287** [comment]
A simple merge commit did it as well :)

**Review by nagmat84 — APPROVED** [review]
Tested and approved.

**Comment by qwerty287** [comment]
Please note that the synced frontend also contains changes from the move from `node-sass` to `sass`, thus the CSS files have changed.

**Pull request merged**
