### PR TITLE
[stacking PR in progress] Refactor image processing to use pipeline instead of hard to read strategy

### PR DESCRIPTION
**Pull request by ildyria**
Feedback welcome.

To enable the code path, set `PHOTO_PIPES=true` in `.env`

### CODE REVIEW

**Comment by ildyria** [comment]
@kamil4 opinion ? 
@d7415 ?
:)

**Comment by ildyria** [comment]
@Kovah heads up.
But I think this should make it easier for you to understand the add photo code flow.

**Comment by Kovah** [comment]
Would have been nice to know this earlier. Spent a few hours trying to get into the structure, and can now spend more time changing everything. Not cool.

**Comment by ildyria** [comment]
> Would have been nice to know this earlier. Spent a few hours trying to get into the structure, and can now spend more time changing everything. Not cool.

Yeah sorry for that, I decided to make the code more readable a bit too late. :(

If you want I can rebase your PR on this one and apply the required changes so you can pick up from there?

**Comment by ildyria** [comment]
@Kovah I went ahead and merged your PR in a new branch and added the required changes to integrate with the new pipe system.
See the branch [s3-pipes](https://github.com/LycheeOrg/Lychee/tree/s3-pipes).

**Comment by ildyria** [comment]
Fully stacked.

**Pull request closed without merging**
