### PR TITLE
refactor diagnostics to use Laravel pipelines

### PR DESCRIPTION
**Pull request by ildyria**
Diagnostics no longer uses auto discovery factory.
This should solve the problem of users just over-writting their configuration when updating Lychee.
See : https://github.com/LycheeOrg/Lychee/issues/1553#issuecomment-1321234867

There is very minimal code change, mostly moving files & matching the Laravel pipeline structure.

### CODE REVIEW

**Comment by eip618** [comment]
> Diagnostics no longer uses auto discovery factory. This should solve the problem of users just over-writting their configuration when updating Lychee. See : [#1553 (comment)](https://github.com/LycheeOrg/Lychee/issues/1553#issuecomment-1321234867)

did i do the upgrade wrong?

**Comment by ildyria** [comment]
> did i do the upgrade wrong?

Not really. Per the [manual update instruction](https://lycheeorg.github.io/docs/update.html#update-manually) it could be said you did it write by simply over-writing all the folders. The problem is that it does not erases already existing files and as a result the automatic detection for diagnostic was working on older files.
Hence this proposal to hard code the diagnostics and remove the automated part.

**Review by qwerty287 — APPROVED** [review]
Did not review the moved files, and I don't know about laravel's pipeline system, but I think this looks good.

**Comment by ildyria** [comment]
> I don't know about laravel's pipeline system, but I think this looks good.

This is a nice example :  https://martinjoo.dev/laravel-pipelines

**Pull request merged**
