### PR TITLE
add Norwegian Bokmål

### PR DESCRIPTION
**Pull request by mulimoen**
I noticed Norwegian was missing, so I've worked from the English language pack to create this pack.

Some phrases were a bit hard to translate, such as "Take Date", and "Star", so I've taken some artistic liberties here. Star -> Stjernemerket is used by the Swedish language pack, and would be understandable by native Norwegian speakers.

### CODE REVIEW

**Review by ildyria — APPROVED** [review]
LGTM.

**Comment by mulimoen** [comment]
Seems I've used the wrong quotation marks in a couple of places. Fixed and rerunning CI.

**Comment by ildyria** [comment]
You did not need to force push every time. Our merging policy is the "Squash and merge" button from github. :)

**Comment by mulimoen** [comment]
I'll keep that in mind for the next one! (:

**Pull request merged**
