### PR TITLE
Add Cloudron Installation Method

### PR DESCRIPTION
**Pull request by nebulade**
We have packaged Lychee since a long time and keept it up-to-date automatically for our users.

### CODE REVIEW

**Comment by d7415** [comment]
I'm not sure about this. If it were to be included, I think it needs to be very clear that it's 3rd party and not supported by LycheeOrg. Then again, for that reason I'd lean against mentioning it in the first place. Happy to see what others think though.

**Comment by nebulade** [comment]
I understand the concern. If it helps, we kept the package up-to-date since a long time now and also usually act as the first level support to triage issues with the app.

Would you actually prefer to put the packaging metadata into a subfolder of the repo itself?

**Comment by ildyria** [comment]
Added to our documentation: https://lycheeorg.github.io/docs/

Source code here: https://github.com/LycheeOrg/LycheeOrg.github.io

**Comment by nebulade** [comment]
Thanks, this looks great!

**Pull request closed without merging**
