### PR TITLE
Add Album loading progress spinner

### PR DESCRIPTION
**Pull request by tinohager**
A loading spinner is displayed for albums with many photos

image

### CODE REVIEW

**Comment by ildyria** [comment]
Why moving out of the promises to async await ?

**Comment by tinohager** [comment]
This is the only way I can really wait with onMounted. I have previously tried to implement it with then. I would generally prefer the await logic.

**Comment by ildyria** [comment]
@tinohager Can you check you are happy with the changes I made ? :)
If so feel free to squash so you have the full ownership of the PR :)

**Comment by tinohager** [comment]
@ildyria Looks good so far, it would probably be even better if it also displayed a text that the photos are currently being loaded.

**Comment by tinohager** [comment]
@d7415 Hi can you review this please :)

**Review by ildyria — APPROVED** [review]

**Pull request merged**
