### PR TITLE
Adjusted with suggested CSS

### PR DESCRIPTION
**Pull request by ildyria**

### CODE REVIEW

**Comment by Colossus68** [comment]
Swipe works.

Scroll does not work for me as expected. Shouldn't the parent element #lychee_sidebar_container contain the overflow-y scroll, not #lychee_sidebar?

That's what worked: 
#lychee_sidebar_container {
    overflow-x: clip;
    overflow-y: auto;
}
#lychee_sidebar {
     padding-right: 15px;
     overflow-wrap: anywhere;
}

**Comment by ildyria** [comment]
@Colossus68  adjusted. Please check :)

**Comment by Colossus68** [comment]
overflow-y-scroll{overflow-y:scoll} missing in public/build/assets/app-B0Q6gW3r.css ?
Whit this it works.

**Comment by ildyria** [comment]
> overflow-y-hidden{overflow-y:hidden} missing in public/build/assets/app-B0Q6gW3r.css ?

You probably need to rebuild the front-end with `npm run build` so that the class is added by tailwind.

**Comment by Colossus68** [comment]
sorry, my fault. Never worked with this bevor. Not a programmer

**Comment by ildyria** [comment]
No worries. :)
You added the correct class, making it work :)

**Review by d7415 — APPROVED** [review]

**Pull request merged**
