### PR TITLE
version 5.0.3

### PR DESCRIPTION
**Pull request by ildyria**

### CODE REVIEW

**Comment by jotka** [comment]
hi @ildyria where do you think you will be releasing 5.03? I'm really looking forward for the APP_URL to be optional :)

**Comment by ildyria** [comment]
> hi @ildyria where do you think you will be releasing 5.03? I'm really looking forward for the APP_URL to be optional :)

I assume you mean when. :)

Simple answer: when all those PR are merged: https://github.com/LycheeOrg/Lychee/milestone/38
But I am waiting for the reviews of my colleagues for that as you can see. :)

**Comment by jotka** [comment]
hi @ildyria  sure, **when** :) thanks a lot!

**Review by qwerty287 — APPROVED** [review]

**Comment by jotka** [comment]
great! 🚀

**Pull request merged**
