### PR TITLE
Bump dependencies with Vite 5 & prevent some more type errors

### PR DESCRIPTION
**Pull request by QuentiumYT**
Hello, this is a small PR that aims to bump to Vite 5. It has received some extra speed and is part of several improvements as well as dropping CJS.

I also added a few `ts-expect-error` directives in albumView as the type was not exactly the same and remove one unneeded. I have a doubt if the script "check" was throwing some `Unused '@ts-expect-error' directive` before, but in some `Alpine.data` types, it is not needed as the type is already correctly casted :) (I was not sure about removing this useless directive)

Also I added the type hint on 2 config files.

Feel free to ask me to split this PR if needed or ask for some changes before merging :)

### CODE REVIEW

**Comment by ildyria** [comment]
Hi Quentin,

thank you for your pull request, unfortunately it seems that node is not so happy with your changes, any luck you could have a look ? :)

**Comment by QuentiumYT** [comment]
Thanks for your quick reply @ildyria, this is what I was talking about `Unused '@ts-expect-error' directive.` is thrown but it is not needed (since now? Idk)

Do you have any clue why this ts-expect was needed, and should I remove them now?

**Comment by ildyria** [comment]
> Do you have any clue why this ts-expect was needed, and should I remove them now?

I guess it was because my IDE was complaining about it. Lemme check your code locally and see if my VSCode is happier. :)

**Comment by ildyria** [comment]
Tested locally, by updating the Alpine Typescript definition it is no longer complaining. :)
So yes you can remove them.
I am pretty sure you are not new to OSS collaboration (given your repo), but next time:
- please make sure to allow access rights to the branch of your repo when you create a pull request (as I am not able to apply those changes).
- do not use the same name as the main/master branch of the repo you are submitting a pull request to. It is not super convenient when push and minor changes are needed.

```
Documents/Projects/Lychee  quentium-master ✔
 ▶ git remote show Quentium-Forks                
* remote Quentium-Forks
  Fetch URL: git@github.com:Quentium-Forks/Lychee.git
  Push  URL: git@github.com:Quentium-Forks/Lychee.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local ref configured for 'git push':
    master pushes to master (local out of date)

Documents/Projects/Lychee  quentium-master ✔  
▶ git push Quentium-Forks quentium-master:master
ERROR: Permission to Quentium-Forks/Lychee.git denied to ildyria.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by QuentiumYT** [comment]
Fine, this is interesting how this fixed 8 old typing issues haha

I am not aware of allowing access rights to the branch, I already seen maintainers pushing to contributor's fork but I don't know where to enable this. I checked [this link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) but is this PR a "user-owned" fork (as Quentium-Forks is an orga)? Could you tell me where I can enable this option? :) Or should I add you as a collaborator?

Regarding the same branch, GitHub propose to clone only the main/master branch so I keep it simple, and I update the branch when I need to contribute again ^^ Depends if it's very different contributions or not, but noted 😉

**Comment by ildyria** [comment]
>  I already seen maintainers pushing to contributor's fork but I don't know where to enable this [...] this PR a "user-owned" fork (as Quentium-Forks is an orga)? Could you tell me where I can enable this option? :) Or should I add you as a collaborator?

No idea.

> Regarding the same branch, GitHub propose to clone only the main/master branch so I keep it simple, and I update the branch when I need to contribute again ^^

I see what you mean. For me it is more in case you would like to improve our code again, then you would need to reset your main branch and pull again from LycheeOrg, while on the other hand, by doing a `git checkout -b new-branch` once you have cloned, it makes it easier to merge later as you just need to delete the branch. :)
I guess it is just a different philosophy. :p

I will let you fix the typescript complaints, re-run the CI and then merge. :+1:

**Comment by QuentiumYT** [comment]
Everything should pass now, waiting for the workflow to run :)

I got your point, I will probably create a new branch when I will contribute the next time to this project.

**Review by ildyria — APPROVED** [review]

**Comment by kamil4** [comment]
> I am not aware of allowing access rights to the branch, I already seen maintainers pushing to contributor's fork but I don't know where to enable this.

I believe that when you submit a PR, there's a tickbox somewhere on that form whether you want to allow the developers to edit your branch or not. I thought it was on by default but maybe I'm misremembering, or maybe it's configurable...

**Comment by QuentiumYT** [comment]
I checked again and I still cannot find it, probably GitHub moving some options around, if I find it one day, i will tick it for sure! :)

**Pull request merged**
