### PR TITLE
Update composer (include breaking)

### PR DESCRIPTION
**Pull request by qwerty287**

### CODE REVIEW

**Comment by ildyria** [comment]
image
The naming of the archive seems to be broken though :(

`Album__getArchive`
and `Album__getArchive (1)`
is what I get now. 
No zip extension.

**Comment by qwerty287** [comment]
This is very weird. In PHP everything seems working - the filename is set correctly in the header. However, the filename does not occur in firefox' network console. If I execute the same via curl, the filename is returned correctly.

**Comment by qwerty287** [comment]
Hmm checked again it does not work with curl too. If I use `curl -I` it works though :thinking: I'll do some more debugging

**Comment by qwerty287** [comment]
Found it. ZipStream got a way to automatically set HTTP headers which is enabled by default and overwrites out headers. I disabled it.

**Review by ildyria — APPROVED** [review]
LGTM.

**Pull request merged**
