### PR TITLE
Fixes for v4.6.4

### LINKED ISSUE #1664: Migration 2022_12_10_183251_increment_user_i_ds failing
Hi there, I was updating to v4.6.4 release using the master branch. Sadly one of the database migration is failig using postgres:

```
   INFO  Running migrations.

  2022_12_10_183251_increment_user_i_ds ................................................................................................... 6ms FAIL

In Connection.php line 760:

  SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "users" violates foreign key constraint "base_albums_owner_id_foreign" on table "base_albums"
  DETAIL:  Key (id)=(0) is still referenced from table "base_albums". (SQL: update "users" set "id" = 1 where "id" = 0)


In Connection.php line 570:

  SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "users" violates foreign key constraint "base_albums_owner_id_foreign" on table "base_albums"
  DETAIL:  Key (id)=(0) is still referenced from table "base_albums".
```

### PR DESCRIPTION
**Pull request by ildyria**
Fixes #1664

### CODE REVIEW

**Comment by ildyria** [comment]
@verymilan this should fix your problem, I tested it locally with pgsql and a user, an album and a photo in the DB.

**Review by qwerty287 — APPROVED** [review]

**Comment by verymilan** [comment]
Thanks a ton, i have applied the diff and the migrations ran through flawlessly. 🎉

**Comment by MartinHennrich** [comment]
I just looked at https://lycheeorg.github.io/demo/#. 
Is that still running on Lychee 4.2.1? Do you plan to update the demo server?

By the way, thanks for your awesome work! 👍

**Comment by ildyria** [comment]
Truth to be told, the demo server... does not exists.
It is just that all the AJAX requests are moked and pre-saved. :')

**Comment by MartinHennrich** [comment]
> Truth to be told, the demo server... does not exists. It is just that all the AJAX requess are moked and pre-saved. :')

Oh 🤣

**Pull request merged**
