### PR TITLE
Fix 1411 visibility propagation

### PR DESCRIPTION
**Pull request by ildyria**

### CODE REVIEW

**Comment by ildyria** [comment]
Just back-end stuff for now.

**Comment by ildyria** [comment]
@nagmat84 are you working on the separation of `is_public` from the album with regard to sharing ?
If so I would drop this PR.

**Comment by nagmat84** [comment]
Yes, I do, but it will probably take about three weeks until I will have something ready.

**Comment by ildyria** [comment]
I will be closing this one for now because #1511 is going to introduce a lot of conflicts and change which makes it more interesting to start working from there.

**Pull request closed without merging**
