### PR TITLE
Add indices to speed up query for album covers

### PR DESCRIPTION
**Pull request by nagmat84**
These missing indices should rectify the performance regression @ildyria has observed. If @ildyria can confirm that these indices do the trick, we should be able to merge.

### CODE REVIEW

**Comment by nagmat84** [comment]
@ildyria If you have already run the migration and don't want to rollback and re-run again, you may also just add the indices manually and check if the performance problem is gone:

    CREATE INDEX photos_album_id_type_index ON photos (album_id, `type`);
    CREATE INDEX photos_album_id_is_starred_created_at_index ON photos (album_id, is_starred, created_at);
    CREATE INDEX photos_album_id_is_starred_taken_at_index ON photos (album_id, is_starred, taken_at);
    CREATE INDEX photos_album_id_is_starred_is_public_index ON photos (album_id, is_starred, is_public);
    CREATE INDEX photos_album_id_is_starred_type_index ON photos (album_id, is_starred, `type`);

**Comment by kamil4** [comment]
Yeah, I sort-of wonder about how reasonable it is to modify existing migrations for code that's already been merged. I think we should create a new one...

**Comment by nagmat84** [comment]
@kamil4 you should also review [LycheeOrg #47](https://github.com/LycheeOrg/LycheeOrg.github.io/pull/47). It gives an explanation.

The main problem is that you cannot add missing indices to an existing table programmatically. You must re-create the whole table. As this is the `photos` table, this means to re-create `albums` (because there are foreign constraints), this means to re-create ... I think you see the problem now.

**Comment by kamil4** [comment]
Yikes!

**Pull request merged**
