### PR TITLE
Fixes missing lychee.locale in main.js

### PR DESCRIPTION
**Pull request by sabian**

### CODE REVIEW

**Comment by ildyria** [comment]
This does no follow our contribution guide.

https://lycheeorg.github.io/docs/contributions.html

**Comment by sabian** [comment]
It's not spam. I'm a beginner at open source and tried to do at least something. Sorry to bother you. Good luck.

**Comment by nagmat84** [comment]
We appreciate every contribution and as you say you are a beginner, I would like to give you some feedback on what you could improve.

> This does no follow our contribution guide.

What @ildyria wants to tell you is that we have a template for pull requests. This template is automatically presented to you when you open a new PR and which provides you with hints on what you are supposed to write. What bug does you PR attempts to fix? What feature or improvement does your PR provide? Etc. pp. However, the description of your PR is completely empty. Without that we do not even have the slightest chance to understand what you PR is about. As there is no chance that you could have missed the template we can only assume that you deliberately ignored it.

On top, your PR has a fundamental technical issue. Your PR "patches" the file `public/dist/main.js`. This file is automatically generated and compiled from the Javascript sources located at [LycheeOrg/Lychee-front](https://github.com/LycheeOrg/Lychee-front). Patching the compiled result won't work, you need to fix the sources.

Hence, if you want to try again you should do as follows

a) create a branch for [LycheeOrg/Lychee-front](https://github.com/LycheeOrg/Lychee-front) and fix the sources
b) create a PR for [LycheeOrg/Lychee-front](https://github.com/LycheeOrg/Lychee-front **and** fill out the provided template for PR such that we can understand what your are doing

If you are a beginner it is completely fine to not get all the details right in the first place. But even as a beginner your should be able to tell other people about our work.

**Comment by sabian** [comment]
Thank you very much

**Comment by sabian** [comment]
Thank you very much

**Pull request closed without merging**
