### PR TITLE
version 4.5.3

### LINKED ISSUE #1432: No suitable image handler found
### Detailed description of the problem 
When trying to upload a photo, after uploading and processing, it fails with the message _No suitable image handler found_

### Output of the diagnostics 
Result of `php artisan lychee:diagnostics`
```
Diagnostics
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.

System Information
------------------
Lychee Version (git):            master (1064f04) -- 5 commits behind master f39be7a (33 minutes ago)
DB Version:                      4.5.2

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       true

System:                          Linux
PHP Version:                     8.1.8
PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
Timezone:                        Europe/Berlin
Max uploaded file size:          64M
Max post size:                   64M
Max execution time:              50000
SQLite Version:                  3.27.2

exec() Available:                yes
Imagick Available:               -
Imagick Enabled:                 0
Imagick Version:                 -
GD Version:                      2.2.5

Config Information
------------------
version:                         040502
check_for_updates:               1
sorting_photos_col:              taken_at
sorting_photos_order:            ASC
sorting_albums_col:              max_taken_at
sorting_albums_order:            ASC
imagick:                         0
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            fr
layout:                          1
image_overlay_type:              date
default_license:                 reserved
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             1
landing_owner:                   L**** L******
landing_title:                   DoubleLShots
landing_subtitle:                Shooting film, not bullets, obvioulsy
landing_facebook:                https://www.facebook.com/doubleLshots
landing_flickr:                  https://www.flickr.com/photos/louislegrain
landing_twitter:                 
landing_instagram:               https://www.instagram.com/doublelshots
landing_youtube:                 
landing_background:              dist/bg.jpg
site_title:                      DoubleLShots
site_copyright_enable:           1
site_copyright_begin:            2022
site_copyright_end:              2022
additional_footer_text:          
display_social_in_gallery:       1
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      0
public_starred:                  0
downloadable:                    1
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           1
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      0
location_decoding:               1
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       1
nsfw_warning:                    1
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1
new_photos_notification:         0
legacy_id_redirection:           1
Content-type: text/html; charset=UTF-8
```
### Error logs :
```
2022-08-02 18:22:20 UTC -- error   -- ::exif_read_data -- 180 -- exif_read_data(lychee-H4_IIjB_N3xTr4nC.jpg): Process tag(x0000=UndefinedTag): Illegal format code 0x0000, suppose BYTE
2022-08-02 18:22:20 UTC -- error   -- App\Image\GdHandler::load -- 191 -- Failed to load image; caused by
2022-08-02 18:22:20 UTC -- error   -- App\Image\ImageHandler::load -- 75 -- No suitable image handler found; caused by
2022-08-02 18:22:20 UTC -- error   -- ::exif_read_data -- 180 -- exif_read_data(lychee-H4_IIjB_N3xTr4nC.jpg): Process tag(x0000=UndefinedTag): Illegal format code 0x0000, suppose BYTE
2022-08-02 18:22:20 UTC -- error   -- App\Image\GdHandler::load -- 191 -- Failed to load image; caused by

```
### Browser and system
Chrome 103.0.5060.134 (official build) (x86_64) on MacOS Cataline 10.15.17

## Some info just in case : 
I'm hosting it on a Ionos (ex 1and1) hosting, it has imagick but renamed into `convert` (located at `/usr/bin/convert`), maybe i could use imagick if i can somehow tell the path to the piece of software who needs it.

**Also** i migrated my lychee, i wiped the folder, pull the last version from the repo, then `composer install --no-dev`, generated keys with artisan, the only thing i kept was the sqlite database and the public/uploads folder

Thanks alot for making Lychee !

### PR DESCRIPTION
**Pull request by ildyria**
version 4.5.3 + composer update to add php-exif v0.7.11

### CODE REVIEW

**Comment by kamil4** [comment]
I would prefer if #1432 is fully resolved before 4.5.3 is released.

**Comment by nagmat84** [comment]
Me, too. Updating php-exif is only half of the solution, we also need to fix `read_exif_data` in Lychee and add a test for it using the broken sample picture.

I am a little bit surprised that we suddenly push out on release after the next.

**Comment by ildyria** [comment]
> I am a little bit surprised that we suddenly push out on release after the next.

I was just matching the tags. Don't overthink it :)

**Comment by nagmat84** [comment]
Why are there so many changes in whitespace? This is annoying.

**Comment by qwerty287** [comment]
This was a php-cs-fixer update.

**Comment by nagmat84** [comment]
> This was a php-cs-fixer update.

That is not a good point. Even if `php-cs-fixer` has been updated, then one can still configure the rules such that the old behaviour is preserved. In this case, the problematic options are `blank_line_between_import_groups` in combination with `imports_order`.

Let's say that we wanted to to change the current behaviour and let's say we decide to be PSR-12 compatible (see https://www.php-fig.org/psr/psr-12/#3-declare-statements-namespace-and-import-statements), then I would understand that. But the current change is not even achieve PSR-12 compatibility, but looks rather random as if nobody took care.

**Comment by nagmat84** [comment]
I added a test case for the bug in https://github.com/LycheeOrg/Lychee/pull/1447/commits/1fd93811f12c47cf39f04405760afd47599ede97, ensured that it triggered the bug reported in https://github.com/LycheeOrg/Lychee/issues/1432 and fixed it in https://github.com/LycheeOrg/Lychee/pull/1447/commits/3ec0160cbbdcf0f7461e0255a3e02458951aec6c.

**Comment by nagmat84** [comment]
I fixed some of the sporadic changes made by CS Fixer in https://github.com/LycheeOrg/Lychee/pull/1447/commits/bab601133bbcdeb7730b9e68a523f0cc3dd91010. I haven't yet found out what newly introduced option controls the removal of parentheses.

Don't get me wrong. I am not against formatting changes. For example, I could envision to move to PSR-12 coding standard. But this decision should be made explicit and it should be in an independent PR. It should not happen accidentally and it should not be mixed with a PR which also introduces functional changes.

**Review by nagmat84 — COMMENTED** [review]
Formally, I am entitled to do a review (as @ildyria is the submitter), but I would prefer if someone else could to a review, because most of the actual changes are on me.

**Comment by ildyria** [comment]
> Formally, I am entitled to do a review (as @ildyria is the submitter), but I would prefer if someone else could to a review, because most of the actual changes are on me.

I can do the review though. :)

**Review by ildyria — COMMENTED** [review]
LGTM. ( I can't click approve though :( )

**Review by kamil4 — APPROVED** [review]

**Comment by kamil4** [comment]
I guess you should be good to go? :smile:

**Pull request merged**
