### PR TITLE
modified logic so we can preserve the image EXIF data if sidecar fails

### PR DESCRIPTION
**Pull request by alex-phillips**

### CODE REVIEW

**Review by ildyria — APPROVED** [review]
Looks good to me, but untested.

**Comment by alex-phillips** [comment]
Hard to tell why this failed on some. Do you guys have any more information?

**Comment by d7415** [comment]
> Hard to tell why this failed on some. Do you guys have any more information?

Looks like it's getting 500 codes back from 3 of the the tests.

```
There were 3 failures:

1) Tests\Feature\PhotosTest::testUpload

Expected status code 200 but received 500.

Failed asserting that 200 is identical to 500.

/home/travis/build/LycheeOrg/Lychee/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:185

/home/travis/build/LycheeOrg/Lychee/tests/Feature/Lib/PhotosUnitTest.php:26

/home/travis/build/LycheeOrg/Lychee/tests/Feature/PhotosTest.php:37

2) Tests\Feature\PhotosTest::test_upload_2

Expected status code 200 but received 500.

Failed asserting that 200 is identical to 500.

/home/travis/build/LycheeOrg/Lychee/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:185

/home/travis/build/LycheeOrg/Lychee/tests/Feature/Lib/PhotosUnitTest.php:26

/home/travis/build/LycheeOrg/Lychee/tests/Feature/PhotosTest.php:37

/home/travis/build/LycheeOrg/Lychee/tests/Feature/PhotosTest.php:201

3) Tests\Feature\RSSTest::testRSS_1

Expected status code 200 but received 500.

Failed asserting that 200 is identical to 500.

/home/travis/build/LycheeOrg/Lychee/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:185

/home/travis/build/LycheeOrg/Lychee/tests/Feature/Lib/PhotosUnitTest.php:26

/home/travis/build/LycheeOrg/Lychee/tests/Feature/RSSTest.php:60
```

**Comment by alex-phillips** [comment]
Is there a way to run these tests locally so I could see the actual 500 error? It looks like the test script is checking for a Travis environment.

**Comment by ildyria** [comment]
you can do `make test` locally if you did `composer install` (thus without the `--no-dev`).
If you add `$response->dump()` before the problematic assert to see what the response look like.

If you have `APP_DEBUG=true` you will see the error content.

**Comment by alex-phillips** [comment]
@tmp-hallenser Hopefully this new logic addresses what you were talking about by it not falling back to the proper metadata. Let me know what you think!

**Pull request merged**
